config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    scope module: 'users' do
      resources :users_skills
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects do
    member do
      get :trainees
      # get :tasks
    end
    scope module: 'projects' do
      resources :evaluations
      resources :tasks do
        member do
          get :trainees
        end
        scope module: 'tasks' do
          resources :reports
        end
      end
    end
  end
  resources :users_projects
  resources :tasks
  resources :projects_tasks
  resources :users_projects_tasks
  resources :tasks_reports
  resources :skills
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @place = Place.first
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/fblogin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook Login JavaScript Example</title>
  <meta charset="UTF-8">
</head>
<body>
<script>

    function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().
        console.log('statusChangeCallback');
        console.log(response);                   // The current login status of the person.
        if (response.status === 'connected') {   // Logged into your webpage and Facebook.
            testAPI();
        } else {                                 // Not logged into your webpage or we are unable to tell.
            document.getElementById('status').innerHTML = 'Please log ' +
                'into this webpage.';
        }
    }


    function checkLoginState() {               // Called when a person is finished with the Login Button.
        FB.getLoginStatus(function(response) {   // See the onlogin handler
            statusChangeCallback(response);
        });
    }


    window.fbAsyncInit = function() {
        FB.init({
            appId      : '482414125892410',
            cookie     : true,                     // Enable cookies to allow the server to access the session.
            xfbml      : true,                     // Parse social plugins on this webpage.
            version    : 'v4.0'           // Use this Graph API version for this call.
        });


        FB.getLoginStatus(function(response) {   // Called after the JS SDK has been initialized.
            statusChangeCallback(response);        // Returns the login status.
        });
    };


    (function(d, s, id) {                      // Load the SDK asynchronously
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));


    function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function(response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
                'Thanks for logging in, ' + response.name + '!';
        });
    }

</script>


//  The JS SDK Login Button

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();" size="large" auto_logout_link="true">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", function(){
          initMap(<%=@place.latitude%>, <%=@place.longitude%>)
      });
  </script>
<% end %>

<% if logged_in? %>
  <div class="center jumbotron">
    <h1>Welcome <%= @current_user.role %> <%= @current_user.name %></h1>

    <% if admin? %>
      <h2>
        You are logged in the website Rikkei Internship
        <br>
        You can manage all users, projects, tasks, skills now!
      </h2>

      <%= link_to "Users", users_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Projects", projects_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Tasks", tasks_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Skills", skills_path, class: "btn btn-lg btn-primary" %>
    <% else %>
      <h2>
        You are logged in the website Rikkei Internship
        <br>
        You can view your projects now!
      </h2>

      <%= link_to "Projects", projects_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Rikkei Internship</h1>

    <h2>
      This is a website to manage Trainees through training projects of Trainers
      <br>
      Would you like to join?
    </h2>

    <%= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-5">
    <h3>
      <b>Công ty TNHH Rikkeisoft Hà Nội</b>
    </h3>
    <h4>
      Tầng 3, Tòa nhà SUDICO (HH3)
    </h4>
    <h4>
      Đường Mễ Trì, Phường Mỹ Đình
    </h4>
    <h4>
      Quận Nam Từ Liêm
    </h4>
    <h4>
      Thành phố Hà Nội, Việt Nam
    </h4>
<!--    <h4 class="find-map">-->
      <%#= link_to "You can find us Google Maps -->", users_projects_path %>
<!--    </h4>-->
  </div>
  <div class="col-md-7">
    <div id="map"></div>
  </div>
</div>