config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    scope module: 'users' do
      resources :users_skills
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects do
    member do
      get :trainees
      # get :tasks
    end
    scope module: 'projects' do
      resources :evaluations
      resources :tasks do
        member do
          get :trainees
        end
        scope module: 'tasks' do
          resources :reports
        end
      end
    end
  end
  resources :users_projects
  resources :tasks
  resources :projects_tasks
  resources :users_projects_tasks
  resources :tasks_reports
  resources :skills
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :trainer, class_name: 'User', foreign_key: 'trainer_id'
  has_many :add_trainees, class_name: 'UsersProject', foreign_key: 'project_id', inverse_of: "project", dependent: :destroy
  has_many :added_trainees, through: :add_trainees, source: :trainee
  has_many :add_tasks, class_name: 'ProjectsTask', foreign_key: 'project_id', inverse_of: "project", dependent: :destroy
  has_many :added_tasks, through: :add_tasks, source: :task
  validates :trainer_id, presence: true
  validates :name, presence: true, length: { maximum: 105 }
  validates :duration, presence: true
  validates :description, length: { maximum: 305 }

  # Add a trainee.
  def add_trainee(trainee)
    added_trainees << trainee
  end

  # Remove a trainee.
  def remove_trainee(trainee)
    added_trainees.delete(trainee)
  end

  # Return true if this project added a trainee.
  def add_trainee?(trainee)
    added_trainees.include?(trainee)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :belong_projects, class_name: "ProjectsTask", foreign_key: "task_id", inverse_of: "task", dependent: :destroy
  has_many :belongs_projects, through: :belong_projects, source: :project
  has_many :belong_users_projects, class_name: "UsersProjectsTask", foreign_key: "task_id", inverse_of: "task", dependent: :destroy
  has_many :belongs_users_projects, through: :belong_users_projects, source: :users_project
  validates :name, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }
  validates :duration, presence: true
  validates :description, length: { maximum: 305 }
end

app/controllers/projects/evaluations_controller.rb
class Projects::EvaluationsController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :index, :destroy] # write in application_controller.rb
  before_action :dont_have_any_project, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_user_project, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_project_evaluation, only: [:show, :edit, :update, :destroy]
  before_action :correct_user_evaluation, only: :show
  before_action :admin_or_trainer, only: [:new, :create, :edit, :update, :destroy]

  def show
    @project = Project.find(params[:project_id])
    if admin?
      @evaluation = Evaluation.find(params[:id])
    elsif trainer?
      @evaluation = current_user.evaluations.find(params[:id])
    elsif trainee?
      @evaluation = current_user.join_projects.find_by(project_id: @project.id).evaluation
    end
  end

  def new
    @project = Project.find(params[:project_id])
    @users_projects = @project.add_trainees.where(status: true)
    if admin?
      @evaluation = Evaluation.new
    elsif trainer?
      @evaluation = current_user.evaluations.build
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @users_projects = @project.add_trainees.where(status: true)
    if admin?
      @evaluation = Evaluation.new(evaluation_params)
    elsif trainer?
      @evaluation = current_user.evaluations.build(evaluation_params)
    end
    if @evaluation.save
      flash[:success] = "Create evaluation successful"
      redirect_to project_evaluation_path(@project.id, @evaluation)
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    if admin?
      @evaluation = Evaluation.find(params[:id])
    elsif trainer?
      @evaluation = current_user.evaluations.find(params[:id])
    end
  end

  def update
    @project = Project.find(params[:project_id])
    if admin?
      @evaluation = Evaluation.find(params[:id])
    elsif trainer?
      @evaluation = current_user.evaluations.find(params[:id])
    end
    if @evaluation.update_attributes(evaluation_params)
      flash[:success] = "Evaluation #{@evaluation.title} has been updated"
      redirect_to project_evaluation_path(@project.id, @evaluation)
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    if admin?
      @evaluation = Evaluation.find(params[:id])
    elsif trainer?
      @evaluation = current_user.evaluations.find(params[:id])
    end
    @evaluation.destroy
    flash[:success] = "Evaluation #{@evaluation.title} has been deleted"
    redirect_to trainees_project_path(@project)
  end

  # Allow change attributes on Web
  def evaluation_params
    if admin? || trainer?
      params.require(:evaluation).permit(:title, :trainer_id, :users_project_id, :working_result, :working_attitude, :manners, :creation)
    end
  end

  def dont_have_any_project
    if current_user.projects.empty? && !admin? && current_user.joined_projects.empty?
      flash[:info] = "You don't have or belong to any project"
      redirect_to projects_url
    end
  end

  def correct_user_project
    @project = Project.find(params[:project_id])
    if !current_user.projects.ids.include?(@project.id) && !admin? && !current_user.joined_projects.ids.include?(@project.id)
      flash[:warning] = "You are not allowed to access project #{@project.name}"
      redirect_to projects_url
    end
  end

  # Confirm an admin or trainer
  def admin_or_trainer
    unless admin? || trainer?
      flash[:warning] = "Just admin or trainer can access that action with evaluation"
      redirect_to projects_url
    end
  end

  # Confirm correct project evaluation when project/id/evaluation/id
  def correct_project_evaluation
    @project = Project.find(params[:project_id])
    @evaluation_w = Evaluation.find(params[:id])
    if @evaluation_w.user_project.project.id != @project.id
      flash[:warning] = "Evaluation doesn't exist or not belongs to project #{@project.name}"
      redirect_to project_url(@project)
    end
  end

  # Confirm correct user can view evaluation when project/id/evaluation/id
  def correct_user_evaluation
    if trainee?
      @evaluation_w = Evaluation.find(params[:id])
      @evaluation = current_user.join_projects.find_by(project_id: @project.id).evaluation
      if @evaluation.present? && @evaluation_w.id != @evaluation.id
        flash[:warning] = "Evaluation not belongs you"
        redirect_to trainees_project_url(@project)
      elsif @evaluation.nil?
        flash[:warning] = "Evaluation doesn't exist or not belongs project #{@project.name}"
        redirect_to project_url(@project)
      end
    end
  end
end

app/controllers/projects/tasks/reports_controller.rb
module Projects
  class Tasks::ReportsController < ApplicationController
    before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :index, :destroy] # write in application_controller.rb
    before_action :dont_have_any_project, only: [:show, :new, :create, :edit, :update, :index, :destroy]
    before_action :correct_user_project, only: [:show, :new, :create, :edit, :update, :destroy, :index]
    before_action :project_include_task, only: [:show, :new, :create, :edit, :update, :destroy, :index]
    before_action :correct_user_project_task, only: [:show, :new, :create, :edit, :update, :destroy, :index]
    before_action :correct_project_report, only: [:show, :edit, :update, :destroy]
    before_action :not_started_task_yet, only: [:show, :new, :create, :edit, :update, :destroy, :index]
    before_action :correct_task_report, only: [:show, :edit, :update, :destroy]
    before_action :trainee_user, only: [:new, :create, :edit, :update, :destroy]

    def show
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      if admin? || trainer?
        @report = Report.find(params[:id])
      elsif trainee?
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
        @reports = @users_projects_task.added_reports
        @report = @reports.find(params[:id])
      end
    end

    def new
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      @users_project = current_user.join_projects.find_by(project_id: @project.id)
      @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
      @report = Report.new
      @report.belong_tasks.build
    end

    def create
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      @users_project = current_user.join_projects.find_by(project_id: @project.id)
      @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
      @report = Report.new(report_params)
      if @report.save
        flash[:success] = "Create Report Successful"
        redirect_to project_task_report_path(@project.id, @task.id, @report)
      else
        render 'new'
      end
    end

    def edit
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      # if admin?
      #   @report = Report.find(params[:id])
      # els
        if trainee?
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
        @reports = @users_projects_task.added_reports
        @report = @reports.find(params[:id])
      end
    end

    def update
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      if admin?
        @report = Report.find(params[:id])
      elsif trainee?
        @report = current_user.reports.find(params[:id])
      end
      if @report.update_attributes(report_params)
        flash[:success] = "Report #{@report.title} has been updated"
        redirect_to project_task_report_path(@project.id, @task.id, @report)
      else
        render 'edit'
      end
    end

    def index
      if trainee?
        @project = Project.find(params[:project_id])
        @task = @project.added_tasks.find(params[:task_id])
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
        @reports = @users_projects_task.added_reports.where(deleted: false).paginate(:per_page => 15, page: params[:page])
      elsif admin? || trainer?
        @project = Project.find(params[:project_id])
        @task = @project.added_tasks.find(params[:task_id])
        @users_projects = @task.belongs_users_projects.where(project_id: @project.id).order(status: :asc).paginate(:per_page => 5, page: params[:page])
      end
    end

    def destroy
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      # if admin? || trainer?
      #   @report = Report.find(params[:id])
      # els
      if trainee?
        @report = current_user.reports.find(params[:id])
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
      end
      @report.update_attributes(deleted: true)
      @report.belong_tasks.find_by(users_projects_task_id: @users_projects_task.id).destroy
      flash[:success] = "Report #{@report.title} has been deleted"
      redirect_to project_task_reports_path(@project.id, @task.id)
    end

    private

    def report_params
      params.require(:report).permit(:trainee_id, :title, :content, belong_tasks_attributes: [:users_projects_task_id])
    end

    def dont_have_any_project
      if current_user.projects.empty? && !admin? && current_user.joined_projects.empty?
        flash[:info] = "You don't have or belong to any project"
        redirect_to projects_url
      end
    end

    def correct_user_project
      @project = Project.find(params[:project_id])
      if !current_user.projects.ids.include?(@project.id) && !admin? && !current_user.joined_projects.ids.include?(@project.id)
        flash[:warning] = "You are not allowed to access project #{@project.name}"
        redirect_to projects_url
      end
    end

    # Confirm a trainee user
    def trainee_user
      @project = Project.find(params[:project_id])
      unless trainee?
        flash[:warning] = "Just trainee can access that action with report"
        redirect_to project_tasks_path(@project.id)
      end
    end

    def correct_project_report
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      @report = Report.find(params[:id])
      if @report.trainee.joined_projects.pluck(:id).exclude?(@project.id)
        flash[:warning] = "Report doesn't exist or not belongs project #{@project.name}"
        redirect_to project_tasks_url(@project)
      end
    end

    # def correct_url
    #   @project = Project.find(params[:project_id])
    #   @task = @project.added_tasks.find(params[:task_id])
    #   # @report = Report.find(params[:id])
    #   if admin? || trainer?
    #     @users_projects = @project.add_trainees
    #     @users_projects.each do |up|
    #       @users_projects_task = up.add_tasks.find_by(task_id: @task.id)
    #       if @users_projects_task.nil?
    #         next
    #       elsif @users_projects_task.present?
    #         @reports = @users_projects_task.added_reports
    #         if @reports.empty?
    #           flash[:warning] = "No reports in task"
    #           redirect_to project_url(@project) and return
    #         else
    #           # if @reports.where(id: params[:id]).exclude?(@report)
    #           #   flash[:warning] = "No man"
    #           #   redirect_to project_url(@project) and return
    #           # end
    #           # @report = @reports.find(params[:id])
    #           @report = @reports.where(id: params[:id])
    #           break
    #         end
    #       end
    #     end
    #   end
    # end

    def not_started_task_yet
      if trainee?
        @project = Project.find(params[:project_id])
        @task = @project.added_tasks.find(params[:task_id])
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
        if @users_projects_task.nil?
          flash[:warning] = "You are not started task #{@task.name} yet"
          redirect_to project_tasks_path(@project.id)
        end
      elsif admin? || trainer?
        @project = Project.find(params[:project_id])
        @task = @project.added_tasks.find(params[:task_id])
        @users_projects = @task.belongs_users_projects.where(project_id: @project.id)
        @users_projects.each do |up|
          @users_projects_task = up.add_tasks.find_by(task_id: @task.id)
          if @users_projects_task.nil?
            flash[:warning] = "No trainees have started this task #{@task.name}"
            redirect_to project_tasks_path(@project.id)
          end
        end
      end
    end

    # Confirm correct report can access
    def correct_task_report
      @project = Project.find(params[:project_id])
      @task = @project.added_tasks.find(params[:task_id])
      if trainee?
        @users_project = current_user.join_projects.find_by(project_id: @project.id)
        @users_projects_task = UsersProjectsTask.find_by(users_project_id: @users_project.id, task_id: @task.id)
        @reports = @users_projects_task.added_reports
        @report = Report.find(params[:id])
        if @reports.exclude?(@report)
          flash[:warning] = "Report doesn't exist or is not yours"
          redirect_to project_tasks_path(@project.id)
        end
      end
    end

    # Confirm project include task when projects/id/task/id
    def project_include_task
      @project = Project.find(params[:project_id])
      @task = Task.find(params[:task_id])
      if @project.added_tasks.ids.exclude?(@task.id)
        flash[:warning] = "Task #{@task.name} hasn't been added to project #{@project.name}"
        redirect_to project_tasks_path(@project.id)
      end
    end

    # Confirm correct task can access
    def correct_user_project_task
      if admin?
        @project = Project.find(params[:project_id])
        @task = Task.find(params[:task_id])

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/tasks/index.html.erb
<% provide(:title, 'Project Tasks') %>
<h1>Tasks of Project <%= link_to @project.name, @project %></h1>

<%if admin? || trainer? %>
  <% if @project.add_trainees.map(&:started).all?{|s| s.nil?} || @project.add_trainees.map(&:finished).all?{|f| f.present?} %>
    <%= link_to 'Create Task', new_task_path, class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Add Task to Project', new_projects_task_path(project_id: @project.id), class: 'btn btn-lg btn-primary' %>
  <% else %>
    <section class="working">
      Just can create, add, update parent for task when trainees are not started yet or completed project.
    </section>
  <% end %>
<% end %>

<br>

<%= will_paginate @tasks %>

<ul class="projects">
  <% @tasks.each do |task| %>
    <% unless task.deleted? %>
      <li>
        <% project_task = @project_tasks.find_by(task_id: task.id) %>
        <h1>
          Task:
          <%= link_to task.name, project_task_path(@project.id, task.id) %>
        </h1>
        <div class="stats">
          <a href=" <%= trainees_project_task_path(@project.id, task.id) %>" class="index-stats">
            <strong class="stat">
              <% if task.belongs_users_projects.where(project_id: @project.id).count == 1 %>
                <%= task.belongs_users_projects.where(project_id: @project.id).count %> trainee
              <% else %>
                <%= task.belongs_users_projects.where(project_id: @project.id).count %> trainees
              <% end %>
            </strong>
          </a>
        </div>
        <% if admin? || trainer? %>
          <% if @project.add_trainees.map(&:started).all?{|s| s.nil?} || @project.add_trainees.map(&:finished).all?{|f| f.present?} %>
            <%= link_to "Update parent task", edit_projects_task_path(project_task), class: 'btn btn-lg btn-primary'%>
          <% end %>
          <%= link_to "Remove", project_task, method: :delete, class: 'btn btn-lg btn-primary', data: { confirm: "Are you sure? If you click OK, data of task, trainees, reports can be lost!" } %>
        <% elsif trainee? && !@users_project.started.nil? %>
          <% users_projects_task = UsersProjectsTask.find_by(task_id: task.id, users_project_id: @users_project.id) %>
          <% if users_projects_task.nil? %>
            <% if project_task.parent.nil? %>
              <%= form_for(@users_projects_task, remote: true ) do |f| %>
                <%= render 'shared/error_messages', object: f.object%>

                <%= hidden_field_tag :users_project_id, @users_project.id %>
                <%= hidden_field_tag :task_id, task.id %>
                <%= hidden_field_tag :started, Date.today %>
                <%= hidden_field_tag :finished, nil %>
                <%= hidden_field_tag :status, false %>

                <%= f.submit "Start", class: "btn btn-lg btn-primary" %>
              <% end %>
            <% elsif project_task.parent.present? && project_task.parent.task.belong_users_projects.find_by(users_project_id: @users_project.id)&.finished.present? %>
              <%= form_for(@users_projects_task, remote: true ) do |f| %>
                <%= render 'shared/error_messages', object: f.object%>

                <%= hidden_field_tag :users_project_id, @users_project.id %>
                <%= hidden_field_tag :task_id, task.id %>
                <%= hidden_field_tag :started, Date.today %>
                <%= hidden_field_tag :finished, nil %>
                <%= hidden_field_tag :status, false %>

                <%= f.submit "Start", class: "btn btn-lg btn-primary" %>
              <% end %>
            <% end %>
          <% elsif !users_projects_task.nil? && !users_projects_task.started.nil? && users_projects_task.finished.nil? %>
            <% if project_task.parent.nil? %>
              <%= form_for(users_projects_task, remote: true) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= hidden_field_tag :users_project_id, @users_project.id  %>
                <%= hidden_field_tag :task_id, task.id %>
                <%= hidden_field_tag :started, users_projects_task.started %>
                <%= hidden_field_tag :finished, Date.today %>
                <%= hidden_field_tag :status, true %>

                <%= f.submit "Finish", class: "btn btn-lg btn-primary", data: { confirm: "Are you sure? Please check task detail, follow it and write reports before finish." } %>
              <% end %>
            <% elsif project_task.parent.present? && project_task.parent.task.belong_users_projects.find_by(users_project_id: @users_project.id)&.finished.present? %>
              <%= form_for(users_projects_task, remote: true) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= hidden_field_tag :users_project_id, @users_project.id  %>
                <%= hidden_field_tag :task_id, task.id %>
                <%= hidden_field_tag :started, users_projects_task.started %>
                <%= hidden_field_tag :finished, Date.today %>
                <%= hidden_field_tag :status, true %>

                <%= f.submit "Finish", class: "btn btn-lg btn-primary", data: { confirm: "Are you sure? Please check task detail, follow it and write reports before finish." } %>
              <% end %>
            <% end %>
          <% elsif !users_projects_task.nil? && !users_projects_task.started.nil? && !users_projects_task.finished.nil? %>
            <section class="completed">
              You have completed this task!
            </section>
          <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= will_paginate @tasks %>

app/views/projects/tasks/new.html.erb
<%# provide(:title, 'New Task') %>
<!--<h1>New Task</h1>-->

<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
    <%#= form_for(@task) do |f| %>
      <%#= render 'shared/error_messages', object: f.object %>

      <%#= f.label :name %>
      <%#= f.text_field :name, class: 'form-control' %>

      <%#= f.label :duration %>
      <%#= f.text_field :duration, class: 'form-control' %>

      <%#= f.label :description %>
      <%#= f.text_area :description, class: 'form-control' %>

      <%#= f.submit "Create task", class: "btn btn-primary" %>
    <%# end %>
<!--  </div>-->
<!--</div>-->

app/views/projects/tasks/show.html.erb
<% provide(:title, "Task #{@task.name}") %>
<h1>Task Info</h1>

<div class="row">
  <aside class="col-md-10">
    <section class="project_info">
      <h1>
        Name:
        <%= @task.name %>
      </h1>
      <h1>
        Duration:
        <%= @task.duration %>
      </h1>
      <h1>
        Description:
        <%= @task.description %>
      </h1>
      <% if admin? %>
        <%= link_to 'Update', edit_task_path(@task), class: 'btn btn-lg btn-primary' %>
        <%= link_to 'Reports', project_task_reports_path(@project.id, @task.id), class: 'btn btn-lg btn-primary' %>
      <% elsif trainer? %>
        <%= link_to 'Reports', project_task_reports_path(@project.id, @task.id), class: 'btn btn-lg btn-primary' %>
      <% elsif trainee? && @users_projects_task.present? %>
        <%= link_to 'Reports', project_task_reports_path(@project.id, @task.id), class: 'btn btn-lg btn-primary' %>
      <% elsif trainee? && @users_projects_task.nil? %>
        <section class="not_started">
          <-- Go back to index tasks page and start the task to create and view report
        </section>
      <% end %>
    </section>
  </aside>
</div>

app/views/projects/tasks/trainees.html.erb
<% provide(:title, 'Task trainees') %>
<h1>Trainees of Task <%= link_to @task.name, project_task_path(@project.id, @task.id) %> in Project <%= link_to @project.name, @project %></h1>

<%= will_paginate @users_projects %>

<ul class="users">
  <% @users_projects.each do |userp| %>
    <% unless userp.trainee.deleted? %>
      <li>
        <% users_projects_task = @users_projects_tasks.find_by(users_project_id: userp.id) %>
        <div class="picture">
          <%= image_tag userp.trainee.picture.url %>
        </div>
        <br>
        <%= link_to userp.trainee.name, userp.trainee %>
        <span>
          Started: <%= users_projects_task.started %>
        </span>
        <span>
          Finished: <%= users_projects_task.finished %>
        </span>

        <span>
          <% if users_projects_task.status.nil? %>
            Status: <span class="not_started">Not started yet</span>
          <% elsif !users_projects_task.status? %>
            Status: <span class="working">Working</span>
          <% else users_projects_task.status? %>
            Status: <span class="completed">Completed</span>
          <% end %>
        </span>
      </li>
    <% end %>
  <% end %>
</ul>

<%= will_paginate  @users_projects %>