config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    scope module: 'users' do
      resources :users_skills
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects do
    member do
      get :trainees
      # get :tasks
    end
    scope module: 'projects' do
      resources :evaluations
      resources :tasks do
        member do
          get :trainees
        end
        scope module: 'tasks' do
          resources :reports
        end
      end
    end
  end
  resources :users_projects
  resources :tasks
  resources :projects_tasks
  resources :users_projects_tasks
  resources :tasks_reports
  resources :skills
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [ :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMap2);
  </script>
<% end %>

<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <p>
    <div id="map2"></div>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", function(){
          initMap(<%=@place.latitude%>, <%=@place.longitude%>)
      });
  </script>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
    <div id="map"></div>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>